# Generated by Django 5.0.3 on 2024-03-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refered_by_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
