# Generated by Django 5.1.3 on 2024-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pcn_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="vehicle_count",
            field=models.IntegerField(default=0),
        ),
    ]
