# Generated by Django 5.1.3 on 2024-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_pcn_count_user_vehicle_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="walletCount",
            field=models.IntegerField(default=0),
        ),
    ]
