# Generated by Django 5.0.3 on 2024-03-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_referalcode_useremailactivationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_date_of_distribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_distrubution_this_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
