# Generated by Django 5.0.3 on 2024-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_date_of_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_distrubution_this_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
