# Generated by Django 5.0.3 on 2024-03-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
