# Generated by Django 5.1.3 on 2024-11-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_home_address_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_for_next_pcn_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
