# Generated by Django 5.1.3 on 2024-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_date_for_next_pcn_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_for_next_pcn_upload',
            field=models.DateField(blank=True, null=True),
        ),
    ]
