# Generated by Django 5.0.3 on 2024-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_company_name_user_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(blank=True, default='FREE', max_length=300, null=True),
        ),
    ]
