# Generated by Django 5.1.3 on 2024-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_date_for_next_pcn_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isSubbedBefore',
            field=models.BooleanField(default=False),
        ),
    ]
