# Generated by Django 5.1.3 on 2024-12-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_is_one_off"),
        ("users", "0009_user_issubbedbefore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="subscriptions.subscription",
            ),
        ),
    ]
