# Generated by Django 3.2.5 on 2024-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_notifications_this_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
