# Generated by Django 5.1.3 on 2025-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document_verification_with_sucess",
            field=models.BooleanField(default=False),
        ),
    ]
