# Generated by Django 3.2.5 on 2024-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
