# Generated by Django 5.0.7 on 2025-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0014_rename_document_verification_with_sucess_user_document_verification_with_success",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
