# Generated by Django 3.2.5 on 2024-06-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_replies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
