# Generated by Django 5.1.2 on 2024-10-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_number_of_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_male',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_date_of_distribution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_distrubution_this_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_notifications_this_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_replies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
