# Generated by Django 5.0.7 on 2024-10-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_is_employer_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.TextField(default='fgfg'),
            preserve_default=False,
        ),
    ]
