# Generated by Django 5.0.7 on 2024-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_home_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("SENT", "SENT"),
                    ("SCHEDULED", "SCHEDULED"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
