# Generated by Django 5.0.7 on 2024-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.CharField(
                blank=True,
                choices=[("QUARTERLY", "QUARTERLY"), ("YEARLY", "YEARLY")],
                max_length=200,
                null=True,
            ),
        ),
    ]
