# Generated by Django 5.0.7 on 2025-06-17 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pcn", models.CharField(max_length=50)),
                ("date_of_notice", models.DateField()),
                ("status", models.TextField(blank=True, null=True)),
                ("ticket_type", models.CharField(max_length=50)),
                (
                    "front_ticket_image",
                    models.ImageField(upload_to="front_ticket_image/"),
                ),
                (
                    "back_ticket_image",
                    models.ImageField(upload_to="back_ticket_image/"),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
