# Generated by Django 5.0.7 on 2025-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="registeration_number",
            field=models.CharField(default="d", max_length=50),
            preserve_default=False,
        ),
    ]
