# Generated by Django 5.1.3 on 2024-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_notifications", "0002_rename_notifications_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="screen",
            field=models.TextField(
                blank=True,
                choices=[("HOME", "Home"), ("TICKETS", "Tickets"), ("PLANS", "Plans")],
                null=True,
            ),
        ),
    ]
