# Generated by Django 5.1.3 on 2024-12-29 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_notifications", "0004_alter_notification_screen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="to_all_registered_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="users_subscription_category",
            field=models.TextField(
                blank=True,
                choices=[("Basic", "Basic"), ("Premium", "Premium"), ("Non", "Non")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
