# Generated by Django 5.1.3 on 2024-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_notifications", "0005_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="users_subscription_category",
            field=models.TextField(
                blank=True,
                choices=[("Basic", "Basic"), ("Premium", "Premium"), ("None", "None")],
                null=True,
            ),
        ),
    ]
