# Generated by Django 5.1.3 on 2024-11-14 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("BASIC", "BASIC"), ("PREMIUM", "PREMIUM")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[("QUARTERLY", "QUARTERLY"), ("YEARLY", "YEARLY")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "date_subscripted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
