# Generated by Django 5.0.7 on 2025-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("BASIC", "BASIC"), ("PREMIUM", "PREMIUM"), ("PLUS", "PLUS")],
                max_length=200,
                null=True,
            ),
        ),
    ]
