# Generated by Django 5.0.7 on 2025-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_subscription_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASIC", "BASIC"),
                    ("STANDARD", "STANDARD"),
                    ("PREMIUM", "PREMIUM"),
                    ("LATE", "LATE"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
