# Generated by Django 5.0.7 on 2024-11-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ("-id",)},
        ),
    ]
