# Generated by Django 5.1.3 on 2024-11-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle_images/"),
        ),
    ]
