# Generated by Django 5.1.3 on 2024-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='duration_in_months',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
