# Generated by Django 5.1.3 on 2024-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0002_discountcode_duration_in_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='duration',
            field=models.CharField(choices=[('ONCE', 'once'), ('REPEATING', 'repeating')], default='forever', max_length=400),
        ),
    ]
