# Generated by Django 5.1.3 on 2025-03-17 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("accepted", models.BooleanField(default=False)),
                ("date_sent", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
