# Generated by Django 5.1.3 on 2025-03-17 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="date_sent",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
