# Generated by Django 5.0.7 on 2024-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCNs", "0002_pcn_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcn",
            name="second_ticket_image",
        ),
        migrations.AddField(
            model_name="pcn",
            name="back_ticket_image",
            field=models.ImageField(default="f", upload_to="back_ticket_image/"),
            preserve_default=False,
        ),
    ]
