# Generated by Django 5.0.7 on 2024-11-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PCNs", "0003_remove_pcn_second_ticket_image_pcn_back_ticket_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pcn",
            options={"ordering": ("-id",)},
        ),
    ]
