# Generated by Django 5.1.3 on 2025-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCNs", "0005_pcn_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcn",
            name="is_denied",
            field=models.BooleanField(default=False),
        ),
    ]
