# Generated by Django 5.1.3 on 2025-03-18 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCNs", "0007_pcn_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcn",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
