# Generated by Django 5.1.3 on 2025-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PCNs", "0008_alter_pcn_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcn",
            name="reason_for_rejection",
            field=models.TextField(blank=True, null=True),
        ),
    ]
